/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controladores.Conectar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.EventQueue;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.io.*;
import java.util.Date;

import org.apache.poi.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.util.IOUtils;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.UnderlinePatterns;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author Traximus
 */
public class Principal extends javax.swing.JFrame {

    public String Numerocliente;

    /**
     * Creates new form Principal
     */
    public Principal() {
        try {
            this.setLocation(350, 210);
            initComponents();
            String sql3="SELECT nro_cta  FROM cuentas";
            ResultSet rs = Conectar.getRegistros(sql3);
            
            
            while (rs.next()) {
                this.jComboBox2.addItem(rs.getObject(1).toString());
                System.out.println(""+rs.getObject(1).toString());
            }
            
            /**
             *
             * @return
             */
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     *
     * @return
     */
    public String getNumerocliente() {
        return Numerocliente;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-register.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/919dd7fa.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("REGISTROS");

        jLabel2.setText("INFORME DE CUENTAS");

        jLabel4.setText("CREAR CUENTA");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abajo.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("INGRESAR DATA");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientes3.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setText("USUARIOS");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo Alcaldia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("BUSQUEDA POR BENEFICIARIO");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", "Anual" }));

        jLabel8.setText("GENERAR INFORMES");

        jLabel9.setText("C I/RIF");

        jLabel10.setText("Informe  general de cuentas  ");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jButton7.setText("r");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setText("RESULTADO DE LA BUSQUEDA");

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Informe por cuenta individual");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton5))
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(7, 7, 7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(15, 15, 15)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(698, 698, 698))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new Hoja());

                frame.pack();
                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CrearCta crear = new CrearCta();
        crear.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new MostrarDatosCta());

                frame.pack();
                frame.setVisible(true);
            }
        });

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();

                try {
                    frame.setContentPane(new Ingresos());
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

                frame.pack();
                frame.setVisible(true);
            }
        });
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Numerocliente = jTextField1.getText();
            String sql = "SELECT *  FROM libro_auxiliar  where rif = '" + Numerocliente + "'";
            ResultSet users = Conectar.getRegistros(sql);
            String mensaje = "WTF DUDE!";
            while (users.next()) {

                jTextArea1.append("Fecha:   " + users.getString(1) + '\n');
                jTextArea1.append("Nro Cheque:   " + users.getString(2) + '\n');
                jTextArea1.append("O/P:  " + users.getString(3) + '\n');
                jTextArea1.append("C/E:  " + users.getString(4) + '\n');
                jTextArea1.append("Beneficiario:   " + users.getString(5) + '\n');
                jTextArea1.append("Rif:  " + users.getString(6) + '\n');
                jTextArea1.append("Descripcion  " + users.getString(7) + '\n');
                Float mnt = users.getFloat(9);
                mnt.toString();
                jTextArea1.append("Monto:" + mnt + '\n');
                jTextArea1.append("________________________________________________________________________________" + '\n');
                jTextArea1.append("" + '\n');

            }

// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();

                frame.setContentPane(new Usuarios());

                frame.pack();
                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String mesb = jComboBox1.getSelectedItem().toString();
if(mesb=="Enero"){
            try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '1' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
           
             HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 //FileInputStream obtains input bytes from the image file
  
 
                 HSSFCell rif = Info.createCell(1);
                 
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
             
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
             celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(10));
             celdadoce.setCellValue(users.getString(11));
             
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Enero";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
             JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Febrero"){
    try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '2' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Febrero";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
    JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Marzo"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '3' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Marzo";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Abril"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '4' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Abril";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Mayo"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '5' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Mayo";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Junio"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '6' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Junio";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Julio"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '7' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Julio";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Agosto"){
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '8' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Agosto";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Septiembre"){
  try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '9' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Septiembre";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
  JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Octubre"){
    try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '10' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Octubre";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
    JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Noviembre"){
   
       try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '11' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Noviembre";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
       JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
}
if(mesb=="Diciembre"){
    
   try {
                
                String sql = "SELECT *  FROM libro_auxiliar  where mes = '12' ORDER BY dia ASC";
                ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
               HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario");
                     enc7.setCellValue("RIF/CI");
                      enc8.setCellValue("Observaciones");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif j-124563");
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
                     celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(11));
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Diciembre";
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jButton7ActionPerformed
    }
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    
        String NumeroCuenta = jComboBox2.getSelectedItem().toString();
       
            try {
                
                 String sql = "SELECT *  FROM libro_auxiliar  where banco = '" + NumeroCuenta + "' ORDER BY mes ASC";
                 ResultSet users = Conectar.getRegistros(sql);
                 HSSFWorkbook libro = new HSSFWorkbook();
             
             //Creamos una instancia de la clase HSSFSheet llamada hoja y la creamos
             HSSFSheet hoja = libro.createSheet();
           
             HSSFRow encabezados = hoja.createRow(0);
              HSSFCell enc1 = encabezados.createCell(1);
              HSSFCell enc2 = encabezados.createCell(2);
              HSSFCell enc3 = encabezados.createCell(3);
              HSSFCell enc4 = encabezados.createCell(4);
              HSSFCell enc5 = encabezados.createCell(5);
              HSSFCell enc6 = encabezados.createCell(6);
              HSSFCell enc7 = encabezados.createCell(7);
              HSSFCell enc8 = encabezados.createCell(8);
              HSSFCell enc9 = encabezados.createCell(9);
              HSSFCell enc10 = encabezados.createCell(10);
              HSSFCell enc11 = encabezados.createCell(11);
              HSSFCell enc12= encabezados.createCell(12);
               enc1.setCellValue("Mes");
                enc2.setCellValue("Dia");
                 enc3.setCellValue("Nro_Cheque");
                  enc4.setCellValue("O/P");
                   enc5.setCellValue("C/E");
                    enc6.setCellValue("Beneficiario___________________________");
                     enc7.setCellValue("RIF/CI_________");
                      enc8.setCellValue("Observaciones____________________________");
                       enc9.setCellValue("Debe");
                        enc10.setCellValue("Haber");
                         enc11.setCellValue("Saldo");
                          enc12.setCellValue("Nro Cta_____________________________");
                          
                HSSFRow Info = hoja.createRow(32);
                 HSSFCell rif = Info.createCell(1);
                      rif.setCellValue("Alcaldia De San Sebastian El Renacer Rif G-20001237-4");
                     
             
                     
                while(users.next()){
                     HSSFRow fila = hoja.createRow(users.getRow());
                     HSSFCell celdauno = fila.createCell(1);
                     HSSFCell celdados = fila.createCell(2);
                     HSSFCell celdatres = fila.createCell(3);
                     HSSFCell celdacuatro = fila.createCell(4);
                     HSSFCell celdacinco = fila.createCell(5);
                     HSSFCell celdaseis = fila.createCell(6);
                     HSSFCell celdasiete = fila.createCell(7);
                     HSSFCell celdaocho = fila.createCell(8);
                     HSSFCell celdanueve = fila.createCell(9);
                     HSSFCell celdadiez = fila.createCell(10);
                     HSSFCell celdaonce = fila.createCell(11);
                     HSSFCell celdadoce = fila.createCell(12);
             
             celdauno.setCellValue(users.getString(12));
             celdados.setCellValue(users.getString(1));
             celdatres.setCellValue(users.getString(2));
             celdacuatro.setCellValue(users.getString(3));
             celdacinco.setCellValue(users.getString(4));
             celdaseis.setCellValue(users.getString(5));
             celdasiete.setCellValue(users.getString(6));
             celdaocho.setCellValue(users.getString(7));
             celdanueve.setCellValue(users.getString(8));
             celdadiez.setCellValue(users.getString(9));
             celdaonce.setCellValue(users.getString(10));
             celdadoce.setCellValue(users.getString(11));
             
             
                System.out.println("Esta Hecho master!"+users.getString(11));
                }
                String ex = "Informe_Cuenta_"+NumeroCuenta;
                FileOutputStream archivo = new FileOutputStream(""+ex+".xls");
             libro.write(archivo);
             archivo.close();
                } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Se ha creado el Excel con exito!!!", "Aviso",1);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
